spring.application.name=boost

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/rewards?allowPublicKeyRetrieval=true&useSSL=false&characterEncoding=UTF-8}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:rewards}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:rewards}

spring.sql.init.mode=always

server.tomcat.max-connections=20000
server.tomcat.accept-count=100000

# Cấu hình Redis Connection Pool được quản lý bởi Redisson (application.yml)
spring.threads.virtual.enabled=true
